"""Initial schema with enterprise models"""

revision = '858467067ff1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datasets_project_id', table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('logs')
    op.drop_index('ix_chats_project_id', table_name='chats')
    op.drop_index('ix_chats_user_id', table_name='chats')
    op.drop_table('chats')
    op.drop_table('settings')
    op.drop_table('db_connection_test')
    op.add_column('cleaned_data', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('cleaned_data', sa.Column('project_id', sa.String(length=36), nullable=False))
    op.add_column('cleaned_data', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('cleaned_data', sa.Column('validated_data_id', sa.String(length=36), nullable=False))
    op.add_column('cleaned_data', sa.Column('parquet_path', sa.Text(), nullable=False))
    op.add_column('cleaned_data', sa.Column('row_count', sa.Integer(), nullable=False))
    op.add_column('cleaned_data', sa.Column('transformations_applied', sa.JSON(), nullable=False))
    op.add_column('cleaned_data', sa.Column('quality_metrics', sa.JSON(), nullable=False))
    op.add_column('cleaned_data', sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='dataprocessingstatus', native_enum=False), nullable=False))
    op.drop_index('ix_cleaned_data_dataset_id', table_name='cleaned_data')
    op.create_index('idx_cleaned_data_session', 'cleaned_data', ['session_id', 'project_id', 'user_id'], unique=False)
    op.create_index('idx_cleaned_data_status', 'cleaned_data', ['status'], unique=False)
    op.create_index(op.f('ix_cleaned_data_project_id'), 'cleaned_data', ['project_id'], unique=False)
    op.create_index(op.f('ix_cleaned_data_session_id'), 'cleaned_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_cleaned_data_user_id'), 'cleaned_data', ['user_id'], unique=False)
    op.drop_constraint('cleaned_data_dataset_id_fkey', 'cleaned_data', type_='foreignkey')
    op.create_foreign_key(None, 'cleaned_data', 'validated_data', ['validated_data_id'], ['id'])
    op.create_foreign_key(None, 'cleaned_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cleaned_data', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cleaned_data', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cleaned_data', 'cleaned_parquet_path')
    op.drop_column('cleaned_data', 'preprocessing_summary')
    op.drop_column('cleaned_data', 'cleaning_summary')
    op.drop_column('cleaned_data', 'dataset_id')
    op.add_column('dashboard', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('dashboard', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('dashboard', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('dashboard', sa.Column('kpi_data', sa.JSON(), nullable=False))
    op.add_column('dashboard', sa.Column('summary_metrics', sa.JSON(), nullable=False))
    op.add_column('dashboard', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
    op.create_index('idx_dashboard_session', 'dashboard', ['session_id', 'project_id', 'last_updated'], unique=False)
    op.create_index(op.f('ix_dashboard_session_id'), 'dashboard', ['session_id'], unique=False)
    op.create_index(op.f('ix_dashboard_user_id'), 'dashboard', ['user_id'], unique=False)
    op.drop_constraint('dashboard_project_id_fkey', 'dashboard', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dashboard', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dashboard', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('feedback', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('feedback', sa.Column('fraud_result_id', sa.String(length=36), nullable=False))
    op.add_column('feedback', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('attached_evidence', sa.JSON(), nullable=False))
    op.add_column('feedback', sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACKNOWLEDGED', 'REJECTED', name='feedbackstatus', native_enum=False), nullable=False))
    op.alter_column('feedback', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('feedback', 'feedback_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('FALSE_POSITIVE', 'FALSE_NEGATIVE', 'CORRECTED_LABEL', name='feedbacktype', native_enum=False),
               existing_nullable=False)
    op.alter_column('feedback', 'corrected_label',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('ix_feedback_dataset_id', table_name='feedback')
    op.drop_index('ix_feedback_result_id', table_name='feedback')
    op.create_index('idx_feedback_session', 'feedback', ['session_id', 'project_id', 'status'], unique=False)
    op.create_index('idx_feedback_type', 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.drop_constraint('feedback_user_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_project_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_dataset_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_result_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback', 'fraud_results', ['fraud_result_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('feedback', 'original_label')
    op.drop_column('feedback', 'notes')
    op.drop_column('feedback', 'result_id')
    op.drop_column('feedback', 'payload')
    op.drop_column('feedback', 'dataset_id')
    op.add_column('fraud_results', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('fraud_results', sa.Column('project_id', sa.String(length=36), nullable=False))
    op.add_column('fraud_results', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('fraud_results', sa.Column('processed_data_id', sa.String(length=36), nullable=False))
    op.add_column('fraud_results', sa.Column('model_decision_path', sa.JSON(), nullable=False))
    op.add_column('fraud_results', sa.Column('shap_values', sa.JSON(), nullable=False))
    op.add_column('fraud_results', sa.Column('feature_contributions', sa.JSON(), nullable=False))
    op.add_column('fraud_results', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('fraud_results', 'row_identifier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('fraud_results', 'predicted_label',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FRAUD', 'REVIEW', 'SAFE', name='predictedlabel', native_enum=False),
               existing_nullable=False)
    op.drop_index('ix_fraud_results_dataset_id', table_name='fraud_results')
    op.drop_index('ix_fraud_results_row_identifier', table_name='fraud_results')
    op.create_index('idx_fraud_results_label_risk', 'fraud_results', ['predicted_label', 'risk_score'], unique=False)
    op.create_index('idx_fraud_results_session', 'fraud_results', ['session_id', 'project_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_fraud_results_project_id'), 'fraud_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_fraud_results_session_id'), 'fraud_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_fraud_results_user_id'), 'fraud_results', ['user_id'], unique=False)
    op.drop_constraint('fraud_results_dataset_id_fkey', 'fraud_results', type_='foreignkey')
    op.create_foreign_key(None, 'fraud_results', 'processed_data', ['processed_data_id'], ['id'])
    op.create_foreign_key(None, 'fraud_results', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fraud_results', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fraud_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fraud_results', 'model_name')
    op.drop_column('fraud_results', 'explanation_text')
    op.drop_column('fraud_results', 'explanation_payload')
    op.drop_column('fraud_results', 'feedback_label')
    op.drop_column('fraud_results', 'affected_features')
    op.drop_column('fraud_results', 'dataset_id')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('CREATED', 'ACTIVE', 'ARCHIVED', name='projectstatus', native_enum=False),
               existing_nullable=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_id', 'created_at'], unique=False)
    op.create_unique_constraint('uk_projects_owner_name', 'projects', ['owner_id', 'name'])
    op.drop_constraint('projects_owner_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('reports', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('reports', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('reports', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('reports', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('findings', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('recommendations', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', 'EXPORTED', name='reportstatus', native_enum=False), nullable=False))
    op.add_column('reports', sa.Column('export_path', sa.Text(), nullable=True))
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('EXECUTIVE', 'TECHNICAL', 'BUSINESS', name='reporttype', native_enum=False),
               existing_nullable=False)
    op.create_index('idx_reports_session', 'reports', ['session_id', 'project_id', 'created_at'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_constraint('reports_project_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('uploads', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.add_column('uploads', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('uploads', sa.Column('status', sa.Enum('RECEIVED', 'PARSING', 'VALIDATED', 'FAILED', name='uploadstatus', native_enum=False), nullable=False))
    op.create_index('idx_uploads_project', 'uploads', ['project_id'], unique=False)
    op.create_index('idx_uploads_session', 'uploads', ['session_id', 'project_id', 'user_id'], unique=False)
    op.create_index('idx_uploads_status', 'uploads', ['status'], unique=False)
    op.create_index(op.f('ix_uploads_session_id'), 'uploads', ['session_id'], unique=False)
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.drop_constraint('uploads_project_id_fkey', 'uploads', type_='foreignkey')
    op.create_foreign_key(None, 'uploads', 'analysis_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'uploads', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('uploads', 'upload_status')
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('auth_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='roleenum', native_enum=False),
               existing_nullable=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['auth_id'])
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.drop_column('users', 'auth_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('uploads', sa.Column('upload_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.create_foreign_key('uploads_project_id_fkey', 'uploads', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_session_id'), table_name='uploads')
    op.drop_index('idx_uploads_status', table_name='uploads')
    op.drop_index('idx_uploads_session', table_name='uploads')
    op.drop_index('idx_uploads_project', table_name='uploads')
    op.drop_column('uploads', 'status')
    op.drop_column('uploads', 'user_id')
    op.drop_column('uploads', 'session_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_project_id_fkey', 'reports', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_session', table_name='reports')
    op.alter_column('reports', 'report_type',
               existing_type=sa.Enum('EXECUTIVE', 'TECHNICAL', 'BUSINESS', name='reporttype', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('reports', 'export_path')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'recommendations')
    op.drop_column('reports', 'findings')
    op.drop_column('reports', 'executive_summary')
    op.drop_column('reports', 'title')
    op.drop_column('reports', 'user_id')
    op.drop_column('reports', 'session_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_owner_id_fkey', 'projects', 'users', ['owner_id'], ['id'])
    op.drop_constraint('uk_projects_owner_name', 'projects', type_='unique')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('CREATED', 'ACTIVE', 'ARCHIVED', name='projectstatus', native_enum=False),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.add_column('fraud_results', sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('fraud_results', sa.Column('affected_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('fraud_results', sa.Column('feedback_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('fraud_results', sa.Column('explanation_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('fraud_results', sa.Column('explanation_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fraud_results', sa.Column('model_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fraud_results', type_='foreignkey')
    op.drop_constraint(None, 'fraud_results', type_='foreignkey')
    op.drop_constraint(None, 'fraud_results', type_='foreignkey')
    op.drop_constraint(None, 'fraud_results', type_='foreignkey')
    op.create_foreign_key('fraud_results_dataset_id_fkey', 'fraud_results', 'datasets', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_fraud_results_user_id'), table_name='fraud_results')
    op.drop_index(op.f('ix_fraud_results_session_id'), table_name='fraud_results')
    op.drop_index(op.f('ix_fraud_results_project_id'), table_name='fraud_results')
    op.drop_index('idx_fraud_results_session', table_name='fraud_results')
    op.drop_index('idx_fraud_results_label_risk', table_name='fraud_results')
    op.create_index('ix_fraud_results_row_identifier', 'fraud_results', ['row_identifier'], unique=False)
    op.create_index('ix_fraud_results_dataset_id', 'fraud_results', ['dataset_id'], unique=False)
    op.alter_column('fraud_results', 'predicted_label',
               existing_type=sa.Enum('FRAUD', 'REVIEW', 'SAFE', name='predictedlabel', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('fraud_results', 'row_identifier',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('fraud_results', 'explanation')
    op.drop_column('fraud_results', 'feature_contributions')
    op.drop_column('fraud_results', 'shap_values')
    op.drop_column('fraud_results', 'model_decision_path')
    op.drop_column('fraud_results', 'processed_data_id')
    op.drop_column('fraud_results', 'user_id')
    op.drop_column('fraud_results', 'project_id')
    op.drop_column('fraud_results', 'session_id')
    op.add_column('feedback', sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('result_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('original_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_result_id_fkey', 'feedback', 'fraud_results', ['result_id'], ['id'])
    op.create_foreign_key('feedback_dataset_id_fkey', 'feedback', 'datasets', ['dataset_id'], ['id'])
    op.create_foreign_key('feedback_project_id_fkey', 'feedback', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('feedback_user_id_fkey', 'feedback', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_index('idx_feedback_type', table_name='feedback')
    op.drop_index('idx_feedback_session', table_name='feedback')
    op.create_index('ix_feedback_result_id', 'feedback', ['result_id'], unique=False)
    op.create_index('ix_feedback_dataset_id', 'feedback', ['dataset_id'], unique=False)
    op.alter_column('feedback', 'corrected_label',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('feedback', 'feedback_type',
               existing_type=sa.Enum('FALSE_POSITIVE', 'FALSE_NEGATIVE', 'CORRECTED_LABEL', name='feedbacktype', native_enum=False),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('feedback', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('feedback', 'status')
    op.drop_column('feedback', 'attached_evidence')
    op.drop_column('feedback', 'comment')
    op.drop_column('feedback', 'fraud_result_id')
    op.drop_column('feedback', 'session_id')
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.create_foreign_key('dashboard_project_id_fkey', 'dashboard', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_dashboard_user_id'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_session_id'), table_name='dashboard')
    op.drop_index('idx_dashboard_session', table_name='dashboard')
    op.drop_column('dashboard', 'last_updated')
    op.drop_column('dashboard', 'summary_metrics')
    op.drop_column('dashboard', 'kpi_data')
    op.drop_column('dashboard', 'title')
    op.drop_column('dashboard', 'user_id')
    op.drop_column('dashboard', 'session_id')
    op.add_column('cleaned_data', sa.Column('dataset_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('cleaned_data', sa.Column('cleaning_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('cleaned_data', sa.Column('preprocessing_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('cleaned_data', sa.Column('cleaned_parquet_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cleaned_data', type_='foreignkey')
    op.drop_constraint(None, 'cleaned_data', type_='foreignkey')
    op.drop_constraint(None, 'cleaned_data', type_='foreignkey')
    op.drop_constraint(None, 'cleaned_data', type_='foreignkey')
    op.create_foreign_key('cleaned_data_dataset_id_fkey', 'cleaned_data', 'datasets', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_cleaned_data_user_id'), table_name='cleaned_data')
    op.drop_index(op.f('ix_cleaned_data_session_id'), table_name='cleaned_data')
    op.drop_index(op.f('ix_cleaned_data_project_id'), table_name='cleaned_data')
    op.drop_index('idx_cleaned_data_status', table_name='cleaned_data')
    op.drop_index('idx_cleaned_data_session', table_name='cleaned_data')
    op.create_index('ix_cleaned_data_dataset_id', 'cleaned_data', ['dataset_id'], unique=False)
    op.drop_column('cleaned_data', 'status')
    op.drop_column('cleaned_data', 'quality_metrics')
    op.drop_column('cleaned_data', 'transformations_applied')
    op.drop_column('cleaned_data', 'row_count')
    op.drop_column('cleaned_data', 'parquet_path')
    op.drop_column('cleaned_data', 'validated_data_id')
    op.drop_column('cleaned_data', 'user_id')
    op.drop_column('cleaned_data', 'project_id')
    op.drop_column('cleaned_data', 'session_id')
    op.create_table('db_connection_test',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='db_connection_test_pkey')
    )
    op.create_table('settings',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='settings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='settings_pkey'),
    sa.UniqueConstraint('user_id', name='settings_user_id_key')
    )
    op.create_table('chats',
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_source', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('context_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='chats_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    op.create_index('ix_chats_user_id', 'chats', ['user_id'], unique=False)
    op.create_index('ix_chats_project_id', 'chats', ['project_id'], unique=False)
    op.create_table('logs',
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='logs_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    op.create_table('datasets',
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_upload_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw_parquet_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('schema_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('merchant_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='datasets_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='datasets_pkey')
    )
    op.create_index('ix_datasets_project_id', 'datasets', ['project_id'], unique=False)
    # ### end Alembic commands ###